add optional vars for custom complete/incomplete paths
linuxserver/docker-transmission pull request #266
Opened 2023-12-05 23:29 UTC by cartfisk

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

 - [ x ] I have read the [contributing](https://github.com/linuxserver/docker-transmission/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Currently the `complete` and `incomplete` download paths are hardcoded. When migrating a large transmission instll to this container it is quite difficult to rewrite paths in Transmission's `.resume` files. This PR allows users to supply a custom path for `download-dir` and `incomplete-dir` to be used in the init script (creating/owning dirs) and writes the path to `settings.json`.

## Benefits of this PR and context:

I recently migrated a large (~2000 xfers) transmission environment from Ubuntu to this container. My existing download-dir is named `completed` and I would like to continue using that name without the complete dir interfering with my tab complete. The process of rewriting transmission's .resume files to match the complete naming convention is tedious and prone to errors.

## How Has This Been Tested?

Ran jenkins-builder!

## Source / References:

https://github.com/linuxserver/docker-transmission/issues/265
https://github.com/linuxserver/docker-transmission/issues/256

2023-12-15 20:07 UTC, nemchik requested changes
The `$` should not be used when setting a variable in a shell script (it can be used to supply a variable as part of the value, but not in front of the variable being set).

Correct ex:
```shell
MY_VAR="My Val and $OTHER_VAR"
```

Incorrect ex:
```shell
$MY_VAR="My Val and $OTHER_VAR"
```

2024-01-16 19:14 UTC, cartfisk commented
@nemchik Made the requested revisions.

2024-02-15 01:20 UTC, nemchik requested changes

2024-02-15 01:20 UTC, nemchik commented on root/etc/s6-overlay/s6-rc.d/init-transmission-config/run
> +    $INIT_COMPLETE_PATH="$COMPLETE_PATH"
```suggestion
    INIT_COMPLETE_PATH="$COMPLETE_PATH"
```

2024-02-15 01:20 UTC, nemchik commented on root/etc/s6-overlay/s6-rc.d/init-transmission-config/run
> +    $INIT_INCOMPLETE_PATH="$INCOMPLETE_PATH"
```suggestion
    INIT_INCOMPLETE_PATH="$INCOMPLETE_PATH"
```

2024-03-06 18:12 UTC, aptalca commented
Thanks for the PR, but I don't see how the paths are hardcoded. There are defaults set in the `setting.json`, but that's user configurable. You can change them to whatever paths you like.

I understand being able to set those in env vars would help with getting it up and running with a single command with migration, but we also need to consider that these advertised new vars will lead to confusion for new users, increased barrier of entry and increased support requests for us.

2024-03-06 18:41 UTC, cartfisk commented
> I don't see how the paths are hardcoded

https://github.com/linuxserver/docker-transmission/pull/266/files#diff-781770b9c6627d58ba2aec8f74dfef0123a06de0f0af3112ed8b83cc4d6ef123L4-L6

The lines above create directories when the container starts if they don't already exist. No matter what is configured in transmission's `config.json`, these hardcoded directories will always be re-created on restart even if they are unused and manually removed from the filesystem.

> I understand being able to set those in env vars would help with getting it up and running with a single command with migration

I mentioned the migration only to illustrate why it's untenable for me to use the default directories. It's not really an ease-of-setup issue, I would just like to prevent these directories from being re-created every restart because the additional directories are a nuisance when navigating via command line. If you can think of another way to accomplish this behavior without the additional variables I would be happy to rework this PR.

I'd argue against the fact that the addition of two optional and pre-configured variables creates any significant barrier-to-entry but then again I am not familiar with the day-to-day of supporting software like this.

2024-03-06 18:50 UTC, aptalca commented
The folder creation is forced, but the path setting is not. You can safely ignore the 2 folders created under /config if you wish to use other paths.

If you want to add logic to not (re)create those 2 folders based on different paths being set in settings.json (behind the scenes, without any additional env vars), I'd be open to that.

2024-03-06 18:52 UTC, cartfisk commented
> If you want to add logic to not (re)create those 2 folders based on different paths being set in settings.json (behind the scenes, without any additional env vars), I'd be open to that.

That sounds fine, I'll give it a shot. Thanks!

2024-03-08 19:19 UTC, closed without merging

2024-03-08 19:20 UTC, cartfisk commented
Here's a new PR w/ revised implementation: https://github.com/linuxserver/docker-transmission/pull/277